# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ItinerarySite.destroy_all
Site.destroy_all
Itinerary.destroy_all
User.destroy_all

ItinerarySite.reset_pk_sequence
Site.reset_pk_sequence
Itinerary.reset_pk_sequence
User.reset_pk_sequence

the_shed = Site.create(name: "The Shed", description: "Designed by Diller Scofidio + Renfro in collaboration with Rockwell Group, the Shed is a $475 million arts center", location: "545 West 30th street New York, N.Y 10001", architectural_style: "Shed", photo_url: "https://media.architecturaldigest.com/photos/5ca64b65409e480bfa72a551/master/w_1600%2Cc_limit/02_The%2520Shed_Photography%2520by%2520Iwan%2520Baan.jpg")
jane_carousel = Site.create(name: "Jane Carousel", description: "Originally built in 1922 and located on the banks of the East River, Brooklyn's Jane's Carousel has become a popular destination to visit.", location: "New Dock st. Brooklyn, NY 11201", architectural_style: "arcylic pavilion", photo_url: "https://media.architecturaldigest.com/photos/59b2b3d7922511310f4e4675/master/w_1600%2Cc_limit/Jane's%2520Carousel.jpg" )
world_trade = Site.create(name: "World Trade Center transportation Hub", description: "The Santiago Calatrava-design World Trade Center Transportation Hub opened in the spring of 2016. From its initial design through to its final completion, the project proved to be arduous for its symbolism, its physical complexity, as well as for the number of commuters it would need to accommodate.", location: "New York, NY 10007", architectural_style: "Urban Infrastructure", photo_url: "https://media.architecturaldigest.com/photos/580fd2f0ef29aecc140f18ef/master/w_1600%2Cc_limit/GettyImages-672094523.jpg" )
ellis_island = Site.create(name: "Ellis Island", description: "Built in 1900 by architects Edward Lippincott Tilton and William A. Boring, Ellis Island was once the gateway for over 12 million immigrants hoping to find a new home in the United States. Today, it is part of the Statue of Liberty National Monument.", location: "Ellis Island",architectural_style: "Renaissance Revival", photo_url: "https://media.architecturaldigest.com/photos/59b2b76d96913d0be00a1fda/master/w_1600%2Cc_limit/Ellis%2520Island.jpg",)
queensboro = Site.create(name: "Queensboro Bridge", description: "Opened in 1909, the Queensboro Bridge is often overlooked due to the legendary Brooklyn Bridge located a few miles south on the East River. Yet, the 3,724-foot-long bridge that connect Manhattan to Queens should not be overlooked.", location: "Ed Koch Queensboro Bridge, New York, NY 10044", architectural_style: "Bridge", photo_url: "https://media.architecturaldigest.com/photos/580fd24579be6d840e3de91c/master/w_1600%2Cc_limit/GettyImages-599658633.jpg")
tower = Site.create(name: "Metropolitan Life Tower", description: "When it was completed in 1909, the Metropolitan Life Tower (pictured on the left) was the world's tallest building (a title it held until 1913)", location: "1 Madison Avenue; Manhattan, New York City", architectural_style: "skyscraper", photo_url: "https://media.architecturaldigest.com/photos/580fcc96ef29aecc140f18ed/master/w_1600%2Cc_limit/GettyImages-576719389.jpg")    
ansonia = Site.create(name: "Ansonia Hotel", description: "Completed in 1904, the Ansonia Hotel is a Beaux Arts–style building with a storied past. It was first conceived as a self-sufficient hotel, and the rooftop was home to a farm with chickens, ducks, and goats (the animals didn’t stay up there long)", location: "2109 Broadway #101, New York, NY 10023", architectural_style: "Beaux-Arts architecture", photo_url: "https://media.architecturaldigest.com/photos/569832e8c6772b7614567104/master/w_1600%2Cc_limit/best-nyc-architectural-landmarks-visit-09.jpg")    
flatiron = Site.create(name: "Flatiron Bluilding", description: "The 22-story, steel-framed Flatiron Building was completed in 1902. Its wedge shape, conceived by architect Daniel Burnham, fit perfectly into the triangular plot that intersects Broadway and Fifth Avenue in Manhattan", location: "175 5th Ave, New York, NY 10010", architectural_style: "Beaux-Arts architecture", photo_url: "https://media.architecturaldigest.com/photos/569833ccc6772b761456710b/master/w_1600%2Cc_limit/best-nyc-architectural-landmarks-visit-12.jpg")
washington = Site.create(name: "Washington Square Park", description: "At nearly ten acres, Washington Square Park is considerably smaller than other New York parks. Yet the densely used green space—which is positioned in the midst of the trendy Greenwich Village neighborhood and includes the beautiful Washington Square Arch—has become a hallmark of the city.", location: "Washington Square, New York, NY 10012", architectural_style: "Monument,", photo_url: "https://media.architecturaldigest.com/photos/5698363b12582c2568829ea4/master/w_1600%2Cc_limit/best-nyc-architectural-landmarks-visit-15.jpg" )
brooklyn = Site.create(name: "Brooklyn Bridge", description: "In 1883, thousands of New Yorkers showed up to the opening ceremony of the Brooklyn Bridge. After 13 years of construction, locals were still concerned over its safety, and to prove its strength, authorities invited a circus entertainer to walk 21 elephants over the bridge.", location: "Brooklyn Bridge, New York, NY 10038", architectural_style: "Bridge", photo_url: "https://media.architecturaldigest.com/photos/56983708c6772b7614567120/master/w_1600%2Cc_limit/best-nyc-architectural-landmarks-visit-17.jpg")
trinity = Site.create(name: "Trinity Church", description: "Trinity Church in downtown Manhattan is located at the intersection of two of the city’s most famous thoroughfares, Broadway and Wall Street. The Gothic Revival structure was completed in 1846 and, at 281 feet tall, was New York’s tallest building at the time. After the attacks on September 11, 2001, the church stood strong, even while modern buildings around it crumbled.", location: "75 Broadway; Manhattan, New York NY 10003", architectural_style: "Gothic Revival", photo_url: "https://media.architecturaldigest.com/photos/56983742c6772b7614567124/master/w_1600%2Cc_limit/best-nyc-architectural-landmarks-visit-18.jpg" )
museum = Site.create(name: "Brooklyn Museum", description: "Located along the western tip of Brooklyn's picturesque Eastern Parkway Blvd, the Brooklyn Museum is a 560,000 square foot museum that contains roughly 1.5 million works of art. Designed by the once prominent architecture firm, McKim, Mead & White, the Beaux-Arts structure is the third largest museum (by way of sheer size).", location: "200 Eastern Pkwy, Brooklyn, NY 11238", architectural_style: "Daniel Chester French", photo_url: "https://media.architecturaldigest.com/photos/5a5e7984fe6075416f119af8/master/w_1600%2Cc_limit/GettyImages-661117833.jpg")
west = Site.create(name: "VIA 57 West", description: "Designed by starchitect, Bjarke Ingels, VIA 57 West is a beautiful residential building that was completed in 2016. The structure has a pyramid-like design with an open-air garden in the middle of structure for tenants to enjoy.", location: "625 W 57th St, New York, NY 10019", architectural_style: "European perimeter block and a traditional Manhattan high-rise", photo_url: "https://media.architecturaldigest.com/photos/5a5e7a010a9a104fe2aec6e4/master/w_1600%2Cc_limit/GettyImages-702546995.jpg")

bleak = User.create(name: "Bleak")

bleaks_itinerary = Itinerary.create(description: "Test Itinerary", name:"Bleak's Itinerary", user: bleak)

itinerary_site_1 = ItinerarySite.create(name: "Itinerary Site 1", site: the_shed, itinerary: bleaks_itinerary)

itinerary_site_2 = ItinerarySite.create(name: "Itinerary Site 1", site: jane_carousel, itinerary: bleaks_itinerary)

puts "Seeded!"